### PR TITLE
feat: init vuepress

### PR DESCRIPTION
**Pull request by whxaxes**
##### Checklist

- [ ] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows commit guidelines

##### Description of change

- 初始化 vuepress
- 添加 guide 部分文档

### CODE REVIEW

**Comment by whxaxes** [comment]
先提交到 1.0 分支，之后全都搞好后再合到 master 吧

**Comment by whxaxes** [comment]
cc @geekdada

**Review by atian25 — APPROVED** [review]

**Comment by whxaxes** [comment]
@geekdada  合到了 1.0 分支了，你可以先开始翻译了

**Comment by geekdada** [comment]
👍

**Pull request merged**
